version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports: 
      - '5432:5432'
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
        - RABBITMQ_DEFAULT_USER=myuser
        - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
  products-service:
    build:
      context: ./products-service
    environment:
      APP_PORT: 8080
      PG_DATABASE: postgres
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USERNAME: postgres
      PG_PASSWORD: 1234
      AMQP_URL: 'amqp://myuser:mypassword@rabbitmq:5672'
      QUEUE: 'productsQueue'
    restart: on-failure
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - '8080:8080'
volumes:
  db-data:
    external: true